### ISSUE TITLE
Handle home-manager versions like nixpkgs?

### ISSUE THREAD

**Issue by kip93** [DeterminateSystems/flakehub-mirror#12]
I can see that there's multiple entries to handle the different supported versions of nixpkgs
```yaml
- repo: NixOS/nixpkgs
  branch: nixos-unstable
- repo: NixOS/nixpkgs
  branch: nixos-22.11
  rolling-minor: 2211
- repo: NixOS/nixpkgs
  branch: nixos-23.05
  rolling-minor: 2305
```
but not for home-manager
```yaml
- repo: nix-community/home-manager
  branch: master
```

maybe there should be something similar? Specially since its versions are very much tied to nixpkgs versions. This way, one can follow the latest stable release of both of them and avoid conflicts when a new release comes out.
